var QUIZ_META = { title: "4-ci sinif üçün məntiq testi", grade: 4 };

var QUESTIONS = [
  { q: "12 × 8 = ?", d: "A", a: "96" },
  { q: "Bir üçbucağın perimetri 36 sm-dir, bütün tərəfləri bərabərdir. Bir tərəfi neçə sm-dir?", d: "O", a: "12" },
  { q: "Düzbucaqlının sahəsi 84 sm², eni 7 sm-dir. Uzunluğu neçə sm-dir?", d: "Ç", a: "12" },
  { q: "144 : 12 = ?", d: "A", a: "12" },
  { q: "Bir ədədi 6-ya böldükdə nəticə 15 olur. Bu ədəd hansıdır?", d: "O", a: "90" },
  { q: "İki ədədin cəmi 156, fərqi 24-dür. Böyük ədəd hansıdır?", d: "Ç", a: "90" },
  { q: "7, 14, 21, 28, … Növbəti iki ədəd hansıdır?", d: "A", a: "35, 42" },
  { q: "Bir sinifdə 36 şagird var, onların 2/3-i qızdır. Neçə oğlan var?", d: "O", a: "12" },
  { q: "Bir zavod hər gün 250 detal istehsal edir. 8 iş günündən sonra 120 detal zay çıxdı. Neçə yararlı detal qalıb?", d: "Ç", a: "1880" },
  { q: "Bir düzbucaqlının uzunluğu 15 sm, eni 9 sm-dir. Perimetri neçədir?", d: "A", a: "48" },
  { q: "Bir kitab mağazasında 3 rəfdə hər birində 45 kitab var. Onlardan 27-si satıldı. Neçə kitab qalıb?", d: "O", a: "108" },
  { q: "Üç ədədin ortalaması 42-dir. İki ədəd 35 və 50-dirsə, üçüncü ədəd neçədir?", d: "Ç", a: "41" },
  { q: "9 × 9 = ?", d: "A", a: "81" },
  { q: "Bir avtobus saatda 65 km sürətlə hərəkət edir. 3 saatda neçə km yol gedər?", d: "O", a: "195" },
  { q: "Bir hovuza saatda 120 litr su axır. Hovuzun tutumu 960 litrdir. Neçə saata dolar?", d: "Ç", a: "8 saat" },
  { q: "500-dən 175 çıx.", d: "A", a: "325" },
  { q: "Bir bağda 8 sıra alma ağacı var, hər sırada 14 ağac var. 3 ağac quruyub. Sağlam ağac sayı neçədir?", d: "O", a: "109" },
  { q: "Bir ədədin yarısının 3 qatı 90-dır. Bu ədəd hansıdır?", d: "Ç", a: "60" },
  { q: "1000-dən 1 əskik ədəd hansıdır?", d: "A", a: "999" },
  { q: "Bir dükanda köynək 45 manata, şalvar köynəkdən 15 manat bahadır. İkisinin qiyməti cəmi neçədir?", d: "O", a: "105" },
  { q: "Sinifdə şagird sayı 5-ə də, 6-ya da tam bölünür və 100-dən kiçikdir. Bu sinifdə ən çoxu neçə şagird ola bilər?", d: "Ç", a: "90" },
  { q: "6 düzbucaqlının hər birinin 4 küncü var. Cəmi neçə künc var?", d: "A", a: "24" },
  { q: "Bir zəncirdə hər halqa əvvəlkindən 4 qram ağırdır. Birinci halqa 5 qramdırsa, 4-cü halqa neçə qramdır?", d: "O", a: "17" },
  { q: "İki ədədin hasili 112, biri digərindən 6 böyükdür. Kiçik ədəd neçədir?", d: "Ç", a: "8" },
  { q: "8 saat = neçə dəqiqə?", d: "A", a: "480" },
  { q: "Bir kitabxanaya kitablar 15-lik bağlamalarla gəlir. 12 bağlama gəlibsə, cəmi neçə kitab var?", d: "O", a: "180" },
  { q: "Bir ədədi 5-ə vurub 8 çıxsaq, nəticə 47 olur. Bu ədəd hansıdır?", d: "Ç", a: "11" },
  { q: "Bir ilin təxminən neçə həftəsi var?", d: "A", a: "52" },
  { q: "Fabrikdə 3 maşın işləyir, hər biri saatda 45 məhsul düzəldir. 4 saatda cəmi neçə məhsul düzəlir?", d: "O", a: "540" },
  { q: "Bir kvadratın perimetri 52 sm-dir. Sahəsi neçə sm²-dir?", d: "Ç", a: "169" },
  { q: "250 + 375 = ?", d: "A", a: "625" },
  { q: "Bir sinifdə şagirdlərin 1/4-i idmançı, 1/3-i musiqiçidir, qalanları isə heç biri deyil. Sinifdə 24 şagird varsa, neçə şagird nə idmançı, nə musiqiçidir?", d: "O", a: "10" },
  { q: "İki dostun pulu cəmi 180 manatdır. Birincinin pulu ikincidən 2 dəfə çoxdur. Hər birinin pulu neçədir?", d: "Ç", a: "60 və 120" },
  { q: "13 × 6 = ?", d: "A", a: "78" },
  { q: "Bir tren saatda 80 km sürətlə 240 km məsafəni neçə saata qət edər?", d: "O", a: "3 saat" },
  { q: "Üç ardıcıl ədədin cəmi 129-dur. Ən böyük ədəd hansıdır?", d: "Ç", a: "44" },
  { q: "720 : 8 = ?", d: "A", a: "90" },
  { q: "Bir mağazada 15 manatlıq məhsulu 20% endirimlə satırlar. Endirimli qiymət neçədir?", d: "O", a: "12" },
  { q: "Bir bağda alma ağacları armud ağaclarının 3 qatından 5 az, armud ağacları 20-dirsə, alma ağacları neçədir?", d: "Ç", a: "55" },
  { q: "Bir düzbucaqlının uzunluğu 12 sm, eni 5 sm-dir. Sahəsi neçədir?", d: "A", a: "60" },
  { q: "6 fəhlə 6 saatda 6 stol düzəldirsə, 12 fəhlə 12 saatda neçə stol düzəldər?", d: "O", a: "24" },
  { q: "Bir ədədin kvadratı 144-dür. Bu ədəd hansıdır?", d: "Ç", a: "12" },
  { q: "5 litr suda neçə ml var?", d: "A", a: "5000" },
  { q: "Bir kitab mağazasında hər kitab 18 manatdır. Elnur 120 manatla neçə kitab ala bilər və neçə manatı qalar?", d: "O", a: "6 kitab, 12 manat qalıq" },
  { q: "İki ədədin ən böyük ortaq böləni 6, ən kiçik ortaq misli 72-dir. Ədədlərdən biri 18-dirsə, digəri neçədir?", d: "Ç", a: "24" },
  { q: "Anar Elnurdan hündürdür, Elnur Turaldan hündürdür, Tural Aygündən hündürdür. Ən uca kimdir?", d: "A", a: "Anar" },
  { q: "Bir avtomobil parkında 45 avtomobil var, onların 2/5-i qırmızıdır. Neçə qırmızı avtomobil var?", d: "O", a: "18" },
  { q: "Bir ədədin 3/4-ü 60-dırsa, ədədin özü neçədir?", d: "Ç", a: "80" },
  { q: "8 × 12 = ?", d: "A", a: "96" },
  { q: "Bir zəngli saat hər gün 3 dəqiqə tez işləyir. 10 gün sonra neçə dəqiqə tez olar?", d: "O", a: "30" },
  { q: "Üç ardıcıl cüt ədədin cəmi 90-dır. Ən kiçik ədəd hansıdır?", d: "Ç", a: "28" },
  { q: "6 saat 45 dəqiqə + 2 saat 30 dəqiqə = ?", d: "A", a: "9 saat 15 dəqiqə" },
  { q: "Bir bağda 60 gül var, onların 1/5-i qırmızı, qalanları ağdır. Neçə ağ gül var?", d: "O", a: "48" },
  { q: "Bir ədədi 7-yə böldükdə bölüm 12, qalıq 3 olur. Bu ədəd hansıdır?", d: "Ç", a: "87" },
  { q: "45 dəqiqə = neçə saniyə?", d: "A", a: "2700" },
  { q: "Bir sinifdə 40 şagird var. Onların yarısı futbol, 1/4-i basketbol oynayır, qalanları heç birini oynamır. Neçə şagird heç birini oynamır?", d: "O", a: "10" },
  { q: "İki ədədin fərqi 18, hasili 175-dir. Böyük ədəd hansıdır?", d: "Ç", a: "25" },
  { q: "3 həftə neçə gündür?", d: "A", a: "21" },
  { q: "Bir fermada 8 sıra pomidor əkilib, hər sırada 25 kol var. 40 kol məhsul vermədi. Neçə kol məhsul verdi?", d: "O", a: "160" },
  { q: "Bir ədədin yarısı ilə üçdə biri arasındakı fərq 15-dir. Bu ədəd hansıdır?", d: "Ç", a: "90" }
];
