var QUIZ_META = { title: "5-ci sinif üçün məntiq testi", grade: 5 };

var QUESTIONS = [
  { q: "15 + 27 × 3 = ?", d: "A", a: "96" },
  { q: "Bir ədədin 40%-i 60-dır. Bu ədəd neçədir?", d: "O", a: "150" },
  { q: "İki ədədin nisbəti 3:5-dir. Böyük ədəd kiçikdən 18 vahid artıqdır. Hər iki ədədi tap.", d: "Ç", a: "27 və 45" },
  { q: "100 − 45 = ?", d: "A", a: "55" },
  { q: "0,25 + 0,75 = ?", d: "O", a: "1" },
  { q: "Düzbucaqlı paralelepipedin ölçüləri 4 sm, 5 sm, 6 sm-dir. Həcmi neçədir?", d: "Ç", a: "120 sm³" },
  { q: "−5 + 8 = ?", d: "A", a: "3" },
  { q: "Bir kvadratın sahəsi 81 sm²-dir. Perimetri neçədir?", d: "O", a: "36 sm" },
  { q: "Bir ədədin 2 qatına 7 əlavə etsək, 31 alınır. Bu ədəd hansıdır?", d: "Ç", a: "12" },
  { q: "12 × 12 = ?", d: "A", a: "144" },
  { q: "Bir sinifin 5/8 hissəsi oğlandır. Sinifdə 40 şagird varsa, neçə qız var?", d: "O", a: "15" },
  { q: "İki ədədin EBOB-u 8, EKOB-u 96-dır. Ədədlərdən biri 24-dürsə, digəri neçədir?", d: "Ç", a: "32" },
  { q: "−12 − 7 = ?", d: "A", a: "−19" },
  { q: "3/4 kəsrini onluq kəsr kimi yaz.", d: "O", a: "0,75" },
  { q: "Mağaza malı 250 manata alıb, 20% qazancla satır. Satış qiyməti neçədir?", d: "Ç", a: "300 manat" },
  { q: "7² = ?", d: "A", a: "49" },
  { q: "Üç ədədin ortalaması 24-dür. Bu ədədlərin cəmi neçədir?", d: "O", a: "72" },
  { q: "Avtomobil 3 saatda 240 km yol gedir. Eyni sürətlə 480 km yolu neçə saata gedər?", d: "Ç", a: "6 saat" },
  { q: "6 × 7 − 5 = ?", d: "A", a: "37" },
  { q: "Bir ədəd 15-ə bölünür və nəticə 8 olur. Bu ədəd hansıdır?", d: "O", a: "120" },
  { q: "x + 15 = 42 tənliyini həll et.", d: "Ç", a: "x = 27" },
  { q: "9 × 6 = ?", d: "A", a: "54" },
  { q: "Bir ədədin 2/5 hissəsi 40-dır. Bu ədəd hansıdır?", d: "O", a: "100" },
  { q: "Hovuzun uzunluğu 12 m, eni 8 m, dərinliyi 2 m-dir. Həcmi neçə m³-dür?", d: "Ç", a: "192 m³" },
  { q: "200 : 4 = ?", d: "A", a: "50" },
  { q: "Bir ədədin yarısı ilə üçdə birinin cəmi 25-dir. Bu ədəd hansıdır?", d: "O", a: "30" },
  { q: "İki ədədin nisbəti 2:7-dir, cəmləri 63-dür. Kiçik ədəd hansıdır?", d: "Ç", a: "14" },
  { q: "15 − (−5) = ?", d: "A", a: "20" },
  { q: "Üçbucağın bucaqları 50°, 60° və x-dir. x bucağı neçə dərəcədir?", d: "O", a: "70°" },
  { q: "4 maşın 4 saatda 400 detal düzəldirsə, 8 maşın 6 saatda neçə detal düzəldər?", d: "Ç", a: "1200 detal" },
  { q: "3,5 + 2,5 = ?", d: "A", a: "6" },
  { q: "Bir ədədin 3 qatından 10 çıxsaq, 50 alınır. Bu ədəd hansıdır?", d: "O", a: "20" },
  { q: "Dükanda qiymət əvvəlcə 20% artırılıb, sonra 20% endirim edilib. Son qiymət ilkin qiymətdən neçə % fərqlənir?", d: "Ç", a: "4% aşağı (96% qalır)" },
  { q: "8 × 9 = ?", d: "A", a: "72" },
  { q: "Dördbucaqlının bütün bucaqlarının cəmi neçə dərəcədir?", d: "O", a: "360°" },
  { q: "Kub şəklində qutunun tərəfi 5 sm-dir. Bütün üzlərinin ümumi sahəsi neçə sm²-dir?", d: "Ç", a: "150 sm²" },
  { q: "−3 × 4 = ?", d: "A", a: "−12" },
  { q: "60-ın 15%-i neçədir?", d: "O", a: "9" },
  { q: "Avtobus A şəhərindən B şəhərinə saatda 60 km sürətlə 4 saata çatır. Geri qayıdanda sürəti 80 km/saat olur. Geri yol neçə saat çəkər?", d: "Ç", a: "3 saat" },
  { q: "100 + 250 = ?", d: "A", a: "350" },
  { q: "Bir ədədin kvadrat kökü 9-dur. Bu ədəd hansıdır?", d: "O", a: "81" },
  { q: "İki ədədin cəmi 84-dür, biri digərinin 3 qatıdır. Kiçik ədəd hansıdır?", d: "Ç", a: "21" },
  { q: "18 : 3 + 4 = ?", d: "A", a: "10" },
  { q: "5 km neçə metrdir?", d: "O", a: "5000" },
  { q: "Zəncirdə hər halqanın çəkisi əvvəlkinin yarısıdır. Birinci halqa 80 qramdırsa, dördüncü halqa neçə qramdır?", d: "Ç", a: "10 qram" },
  { q: "4 + 5 × 2 = ?", d: "A", a: "14" },
  { q: "Maşın 100 km yolu 8 litr benzinlə gedir. 250 km yol üçün neçə litr benzin lazımdır?", d: "O", a: "20 litr" },
  { q: "Üç ədəd ardıcıl 3-ə bölünən ədədlərdir, cəmləri 45-dir. Ən böyük ədəd hansıdır?", d: "Ç", a: "18" },
  { q: "6² − 10 = ?", d: "A", a: "26" },
  { q: "Dairənin radiusu 7 sm-dir. Diametri neçədir?", d: "O", a: "14 sm" },
  { q: "Bir hovuzu birinci muslu tək halda 4 saata, ikinci muslu tək halda 4 saata doldurur. Hər ikisi birlikdə açılsa, hovuz neçə saata dolar?", d: "Ç", a: "2 saat" },
  { q: "90 − 35 = ?", d: "A", a: "55" },
  { q: "1000 manata illik 5% sadə faiz tətbiq olunur. 1 ildən sonra faiz məbləği neçədir?", d: "O", a: "50 manat" },
  { q: "Avtomobil parkında avtomobillərin sayı motosikletlərdən 3 dəfə çoxdur. Cəmi nəqliyyat vasitəsi 96-dırsa, motosiklet sayı neçədir?", d: "Ç", a: "24" },
  { q: "11 × 11 = ?", d: "A", a: "121" },
  { q: "Kubun həcmi 64 sm³-dür. Tərəfi neçə sm-dir?", d: "O", a: "4 sm" },
  { q: "EBOB-u 12 olan ən kiçik üç ədədi yaz (12-nin mislərindən).", d: "Ç", a: "12, 24, 36" },
  { q: "2/4 kəsri neçə faizdir?", d: "A", a: "50%" },
  { q: "2, 6, 18, 54, … Növbəti ədəd hansıdır?", d: "O", a: "162" },
  { q: "Dördbucaqlının en və uzunluq nisbəti 3:4-dür. Perimetri 84 sm-dirsə, sahəsi neçədir?", d: "Ç", a: "432 sm²" }
];
