var QUIZ_META = { title: "3-ci sinif üçün məntiq testi", grade: 3 };

var QUESTIONS = [
  { q: "5, 10, 15, 20, … Növbəti iki ədəd hansıdır?", d: "A", a: "25, 30" },
  { q: "İki rəqəmli ədədəm. Rəqəmlərimin cəmi 11-dir, onlarlığım vahidliyimdən 3 böyükdür. Mən hansı ədədəm?", d: "O", a: "74" },
  { q: "Üç bacı-qardaşın yaşları ardıcıl cüt ədədlərdir (məs: 10, 12, 14). Yaş cəmləri 36-dır. Hər birinin yaşı neçədir?", d: "Ç", a: "10, 12, 14" },
  { q: "Anar 3 alma yedi, sonra dükandan 5 alma aldı və indi 10 alması var. Əvvəlcə neçə alması var idi?", d: "A", a: "8" },
  { q: "Bir mağazada qələmlər 4-lük dəstələrdə satılır. Vüsal 6 dəstə aldı, sonra 9 qələm istifadə etdi. Neçə qələmi qalıb?", d: "O", a: "15" },
  { q: "Ata, ana və uşağın yaş cəmi 90-dır. Ata anadan 4 yaş böyükdür, uşaq 10 yaşındadır. Ana neçə yaşındadır?", d: "Ç", a: "38" },
  { q: "Zeynəbin 3 pişiyi var, hər pişiyin 4 pəncəsi var. Cəmi neçə pəncə var?", d: "A", a: "12" },
  { q: "Bir kitabın yarısını oxudum, qalan hissəsi 60 səhifədir. Kitabda cəmi neçə səhifə var?", d: "O", a: "120" },
  { q: "İki qutuda cəmi 60 alma var. Birinci qutuda ikincidən 2 dəfə çox alma var. Hər qutuda neçə alma var?", d: "Ç", a: "20 və 40" },
  { q: "50, 45, 40, 35, … Növbəti iki ədəd hansıdır?", d: "A", a: "30, 25" },
  { q: "Turqut Aygündən sürətli qaçır, Aygün Kəmalədən sürətli qaçır, Kəmalə Elvindən sürətli qaçır. Ən yavaş kimdir?", d: "O", a: "Elvin" },
  { q: "Bir zəncirdə hər halqa əvvəlkindən 3 dəfə ağırdır. Birinci halqa 2 qramdırsa, üçüncü halqa neçə qramdır?", d: "Ç", a: "18" },
  { q: "Bir toyuq 2 gündə 2 yumurta yumurtlayırsa, 6 toyuq 6 gündə neçə yumurta yumurtlayar?", d: "A", a: "36" },
  { q: "Aygülün pulu Elnurundan 15 manat çoxdur. Onların pullarının cəmi 55 manatdır. Elnurun pulu neçədir?", d: "O", a: "20" },
  { q: "Dərs saat 09:15-də başladı və 3 saat 40 dəqiqə çəkdi. Dərs neçədə bitdi?", d: "Ç", a: "12:55" },
  { q: "Bir maşında 4 təkər var. 9 maşında cəmi neçə təkər var?", d: "A", a: "36" },
  { q: "Bir bağda alma ağacları armud ağaclarından 4 dəfə çoxdur. Armud ağacları 6 ədəddirsə, alma ağacları neçədir?", d: "O", a: "24" },
  { q: "İki rəqəmli ədədəm. Vahidliyim onlarlığımdan 5 böyükdür, rəqəmlərimin cəmi 9-dur. Mən hansı ədədəm?", d: "Ç", a: "27" },
  { q: "Cümə axşamından sonra hansı gün gəlir?", d: "A", a: "Cümə" },
  { q: "3 uşağın hər birinə 5 şokolad paylandı, sonra əlavə 4 şokolad da paylandı. Cəmi neçə şokolad paylanıb?", d: "O", a: "19" },
  { q: "4 dülgər 4 stolu 4 gündə düzəldirsə, 8 dülgər 8 stolu neçə gündə düzəldər?", d: "Ç", a: "4 gün" },
  { q: "12, 14, 16, 18, … Növbəti iki ədəd hansıdır?", d: "A", a: "20, 22" },
  { q: "Sinifin 3/5 hissəsi qızdır. Sinifdə 30 şagird varsa, neçə qız var?", d: "O", a: "18" },
  { q: "Vüsal Elnurdan 2 dəfə çox pula malikdir, Elnur isə Kamaldan 3 manat çoxdur. Kamalın 5 manatı var. Vüsalın pulu neçədir?", d: "Ç", a: "16" },
  { q: "Bir qutuda 24 karandaş var. Onları 6 uşağa bərabər paylasaq, hər birinə neçə düşər?", d: "A", a: "4" },
  { q: "Saat 10:00-da başlayan film 2 saat 15 dəqiqə çəkir. Film neçədə bitir?", d: "O", a: "12:15" },
  { q: "Məni 4-ə vur, 6 çıx — nəticə 18 olur. Mən hansı ədədəm?", d: "Ç", a: "6" },
  { q: "Bağda 7 qırmızı, 5 sarı gül var. Cəmi neçə gül var?", d: "A", a: "12" },
  { q: "Kitab rəflərində 5 rəf var, hər birində 12 kitab olmalıdır, amma 2 rəfdə 3-ər kitab əskikdir. Cəmi neçə kitab var?", d: "O", a: "54" },
  { q: "3 il əvvəl Elnurun yaşı indiki yaşının yarısı idi. Elnur indi neçə yaşındadır?", d: "Ç", a: "6" },
  { q: "Bir həftədə neçə gün var?", d: "A", a: "7" },
  { q: "Pəncərədə əvvəlcə 8 quş var idi. Hamısı uçub getdi, sonra əvvəlkindən 3 dəfə çox quş qondu. İndi pəncərədə neçə quş var?", d: "O", a: "24" },
  { q: "İki ədədin cəmi 40, fərqi 8-dir. Böyük ədəd hansıdır?", d: "Ç", a: "24" },
  { q: "3 üçbucağın hər birinin 3 küncü var. Cəmi neçə künc var?", d: "A", a: "9" },
  { q: "1 kq alma 3 manatdır. Aynur 4 kq alma aldı və 20 manatlıq pulla ödədi. Neçə manat qalığı oldu?", d: "O", a: "8" },
  { q: "İki rəqəmli ədədəm. Rəqəmlərimin hasili 12-dir, cəmi 7-dir. Mən hansı ədədəm?", d: "Ç", a: "34 (və ya 43)" },
  { q: "9, 18, 27, 36, … Növbəti ədəd hansıdır?", d: "A", a: "45" },
  { q: "Sürücü 60 km yolu 2 saata gedir. Eyni sürətlə 90 km yolu neçə saata gedər?", d: "O", a: "3 saat" },
  { q: "Anar Vüsaldan öndədir, Elnur isə Anardan öndədir. Yarışda sıralama necədir?", d: "Ç", a: "Elnur, Anar, Vüsal" },
  { q: "Bir əldə 5 barmaq var. 2 əldə cəmi neçə barmaq var?", d: "A", a: "10" },
  { q: "45 şagirddən 27-si oğlandır. Neçə qız var?", d: "O", a: "18" },
  { q: "Bir zəncirdə hər halqa əvvəlkindən 5 qram ağırdır. Birinci halqa 4 qramdırsa, beşinci halqa neçə qramdır?", d: "Ç", a: "24" },
  { q: "Bağçada 6 sıra tərəvəz var, hər sırada 8 kök var. Cəmi neçə kök var?", d: "A", a: "48" },
  { q: "Orxan gündə 15 səhifə oxuyur. 240 səhifəlik kitabı neçə günə bitirər?", d: "O", a: "16" },
  { q: "Üç ədədin ortalaması 15-dir. İki ədəd 10 və 18-dirsə, üçüncü ədəd neçədir?", d: "Ç", a: "17" },
  { q: "Bir litr suda 1000 ml var. Yarım litr neçə ml-dir?", d: "A", a: "500" },
  { q: "Hər zərfdə 25 manat var. 6 zərfdə cəmi neçə manat var?", d: "O", a: "150" },
  { q: "İki bacının yaş cəmi 26-dır. Böyüyü kiçikdən 4 yaş böyükdür. Hər birinin yaşı neçədir?", d: "Ç", a: "11 və 15" },
  { q: "8 + 7 = ?", d: "A", a: "15" },
  { q: "Zavod hər saat 40 detal düzəldir. 5 saat işlədikdən sonra 30 detal zay çıxdı. Neçə yararlı detal qalıb?", d: "O", a: "170" },
  { q: "Bir ədəd özü-özünə vurulanda 49 alınır. Bu ədəd hansıdır?", d: "Ç", a: "7" },
  { q: "Bir ildə neçə ay var?", d: "A", a: "12" },
  { q: "50 manatlıq alış-verişdən 10 manat endirim edilir. Ödəniləcək məbləğ neçədir?", d: "O", a: "40" },
  { q: "Üç dostun kitab sayı ardıcıl ədədlərdir, cəmi 24-dür. Ən çox kitabı olan dostun neçə kitabı var?", d: "Ç", a: "9" },
  { q: "100-dən 1 əskik olan ədəd hansıdır?", d: "A", a: "99" },
  { q: "18 şagirdi 3 nəfərlik qruplara bölürlər. Neçə qrup alınar?", d: "O", a: "6" },
  { q: "Bir konteynerdə alma armuddan 3 dəfə çoxdur. Cəmi 200 meyvə varsa, armud neçədir?", d: "Ç", a: "50" },
  { q: "6 − 4 = ?", d: "A", a: "2" },
  { q: "Zəngli saat hər gün 5 dəqiqə tez işləyir. 4 gün sonra neçə dəqiqə tez olar?", d: "O", a: "20" },
  { q: "İki ədədin hasili 32-dir, biri digərindən 2 dəfə böyükdür. Kiçik ədəd neçədir?", d: "Ç", a: "4" }
];
