var QUIZ_META = { title: "7-ci sinif üçün məntiq testi", grade: 7 };

var QUESTIONS = [
  { q: "−3/4 və −1/2 ədədlərindən hansı böyükdür?", d: "A", a: "−1/2" },
  { q: "a³ · a⁴ ifadəsini sadələşdir.", d: "A", a: "a⁷" },
  { q: "(a²)³ ifadəsini sadələşdir.", d: "O", a: "a⁶" },
  { q: "x⁵ : x² ifadəsini sadələşdir.", d: "A", a: "x³" },
  { q: "(x + 3)² ifadəsini aç.", d: "O", a: "x² + 6x + 9" },
  { q: "(2x − 5)² ifadəsini aç.", d: "Ç", a: "4x² − 20x + 25" },
  { q: "a² − b² ifadəsini vuruqlara ayır.", d: "O", a: "(a − b)(a + b)" },
  { q: "Müxtəsər vurma düsturundan istifadə edərək 47² − 43²-i hesabla.", d: "Ç", a: "360" },
  { q: "1000 manata illik 10% sadə faiz tətbiq olunur. 2 ilin sonunda faiz məbləği neçədir?", d: "A", a: "200 manat" },
  { q: "1000 manata illik 10% mürəkkəb faizlə 2 il sonra əmanətin son məbləği neçə olar?", d: "Ç", a: "1210 manat" },
  { q: "3x + 7 = 22 tənliyini həll et.", d: "A", a: "x = 5" },
  { q: "2x − 5 = x + 9 tənliyini həll et.", d: "O", a: "x = 14" },
  { q: "x + y = 10, x − y = 4 tənliklər sistemini həll et.", d: "Ç", a: "x = 7, y = 3" },
  { q: "2x + y = 11, x − y = 1 tənliklər sistemini həll et.", d: "Ç", a: "x = 4, y = 3" },
  { q: "|x| = 7 tənliyini həll et.", d: "A", a: "x = 7 və ya x = −7" },
  { q: "|x − 3| = 5 tənliyini həll et.", d: "O", a: "x = 8 və ya x = −2" },
  { q: "(3x² + 2x) + (x² − 5x) ifadəsini sadələşdir.", d: "A", a: "4x² − 3x" },
  { q: "(5x² − 3x + 2) − (2x² + x − 4) ifadəsini sadələşdir.", d: "O", a: "3x² − 4x + 6" },
  { q: "(x + 2)(x + 5) hasilini aç.", d: "Ç", a: "x² + 7x + 10" },
  { q: "Üçbucağın iki bucağı 40° və 70°-dir. Üçüncü bucaq neçə dərəcədir?", d: "A", a: "70°" },
  { q: "Üçbucağın xarici bucağı 110°-dir, ona qonşu olmayan daxili bucaqlardan biri 50°-dir. Digəri neçədir?", d: "O", a: "60°" },
  { q: "Üçbucağın bucaqları nisbəti 2:3:4-dür. Ən böyük bucaq neçə dərəcədir?", d: "Ç", a: "80°" },
  { q: "İki paralel düz xətti kəsən düz xətt bucaqlardan birini 65° yaradır. Bu bucağa uyğun olan bucaq neçədir?", d: "A", a: "65°" },
  { q: "İki paralel düz xətti kəsən düz xətt zamanı daxili çarpaz bucaqlardan biri 72°-dir. Digəri neçədir?", d: "O", a: "72°" },
  { q: "İki paralel düz xətti kəsən düz xətt zamanı bir tərəfli daxili bucaqların cəmi neçədir?", d: "Ç", a: "180°" },
  { q: "Üçbucağın konqruyentliyinin neçə əsas əlaməti var?", d: "A", a: "3" },
  { q: "İki üçbucağın uyğun tərəfləri bərabərdir: 5, 7, 9 sm və 5, 7, 9 sm. Bu üçbucaqlar hansı əlamətə görə konqruyentdir?", d: "O", a: "Tərəf-tərəf-tərəf (TTT)" },
  { q: "y = 2x + 3 funksiyasında x = 4 olduqda y neçədir?", d: "A", a: "11" },
  { q: "y = −x + 6 funksiyasının qrafiki OX oxunu hansı nöqtədə kəsir?", d: "O", a: "(6, 0)" },
  { q: "y = 3x − 6 funksiyasının qrafiki koordinat oxları ilə kəsişmə nöqtələrini tap.", d: "Ç", a: "(2, 0) və (0, −6)" },
  { q: "A(4, 5) nöqtəsinin koordinat başlanğıcına nəzərən mərkəzi simmetrik nöqtəsini tap.", d: "A", a: "(−4, −5)" },
  { q: "B(−3, 7) nöqtəsinin koordinat başlanğıcına nəzərən mərkəzi simmetrik nöqtəsi hansıdır?", d: "O", a: "(3, −7)" },
  { q: "Zər (kub) bir dəfə atılır. Cəmi neçə elementar hadisə (mümkün nəticə) var?", d: "A", a: "6" },
  { q: "Zər atılanda cüt ədəd və ya 5 gəlməsinin ehtimalını tap.", d: "O", a: "2/3" },
  { q: "Bir torbada 4 qırmızı, 3 göy kürə var. Təsadüfən çıxarılan kürənin qırmızı və ya göy olması ehtimalı neçədir?", d: "Ç", a: "1" },
  { q: "−7 + 12 = ?", d: "A", a: "5" },
  { q: "−2/3 + 1/6 = ?", d: "O", a: "−1/2" },
  { q: "(−3)³ − 2⁴ = ?", d: "Ç", a: "−43" },
  { q: "5x = 45 tənliyini həll et.", d: "A", a: "x = 9" },
  { q: "3(x − 2) = 15 tənliyini həll et.", d: "O", a: "x = 7" },
  { q: "2(x + 3) − (x − 1) = 12 tənliyini həll et.", d: "Ç", a: "x = 5" },
  { q: "a⁶ : a³ = ?", d: "A", a: "a³" },
  { q: "(2a)³ ifadəsini sadələşdir.", d: "O", a: "8a³" },
  { q: "(a + b)² − (a − b)² ifadəsini sadələşdir.", d: "Ç", a: "4ab" },
  { q: "Üçbucağın bucaqlarının cəmi neçə dərəcədir?", d: "A", a: "180°" },
  { q: "Düzbucaqlı üçbucağın iti bucaqlarından biri 35°-dir. Digər iti bucaq neçədir?", d: "O", a: "55°" },
  { q: "Üçbucağın bir bucağı digərindən 2 dəfə, üçüncüsü isə birincidən 3 dəfə böyükdür. Ən kiçik bucaq neçədir?", d: "Ç", a: "30°" },
  { q: "25% ilə 1/4 kəsrinin cəmi neçədir?", d: "A", a: "1/2 (50%)" },
  { q: "500 manata illik 6% sadə faizlə 3 ilin faizi neçədir?", d: "O", a: "90 manat" },
  { q: "2000 manata illik 5% mürəkkəb faizlə 2 il sonra məbləğ neçə olar?", d: "Ç", a: "2205 manat" },
  { q: "2x + 3y = 12 tənliyində x = 0 olduqda y neçədir?", d: "A", a: "y = 4" },
  { q: "x − 2y = 4 və x + y = 10 tənliklər sistemini həll et.", d: "O", a: "x = 8, y = 2" },
  { q: "3x + 2y = 16, x − y = 2 tənliklər sistemini həll et.", d: "Ç", a: "x = 4, y = 2" },
  { q: "Üçbucağın konqruyentlik əlamətlərindən \"tərəf-bucaq-tərəf\"dən başqa digər ikisini yaz.", d: "A", a: "Tərəf-tərəf-tərəf; bucaq-tərəf-bucaq" },
  { q: "|2x − 4| = 10 tənliyini həll et.", d: "O", a: "x = 7 və ya x = −3" },
  { q: "|x + 5| = 3x − 1 tənliyini həll et.", d: "Ç", a: "x = 3" },
  { q: "y = 4x − 1 funksiyasında x = 2 olduqda y neçədir?", d: "A", a: "7" },
  { q: "Üçbucağın perimetri 36 sm-dir, tərəfləri nisbəti 3:4:5-dir. Ən uzun tərəf neçədir?", d: "O", a: "15 sm" },
  { q: "M(2, −3) nöqtəsinin koordinat başlanğıcına nəzərən mərkəzi simmetrik nöqtəsini tap.", d: "Ç", a: "(−2, 3)" },
  { q: "Bir torbada 5 qara, 5 ağ kürə var. Təsadüfən çıxarılan kürənin qara olması ehtimalı neçədir?", d: "A", a: "1/2" }
];
