var QUIZ_META = { title: "6-ci sinif üçün məntiq testi", grade: 6 };

var QUESTIONS = [
  { q: "−8 + 15 = ?", d: "A", a: "7" },
  { q: "Bir ədədin −3 ilə hasili 21-dir. Bu ədəd hansıdır?", d: "O", a: "−7" },
  { q: "İki ədədin nisbəti 4:9-dur, fərqləri 25-dir. Böyük ədəd hansıdır?", d: "Ç", a: "45 (kiçik: 20)" },
  { q: "|−12| = ?", d: "A", a: "12" },
  { q: "0,4 kəsrini faizlə ifadə et.", d: "O", a: "40%" },
  { q: "Dairənin radiusu 7 sm-dir (π ≈ 22/7). Çevrəsini (uzunluğunu) tap.", d: "Ç", a: "44 sm" },
  { q: "−6 × (−4) = ?", d: "A", a: "24" },
  { q: "x − 9 = 15 tənliyini həll et.", d: "O", a: "x = 24" },
  { q: "Bir avtomobil 350 km yolu 7 saata gedir. Sürəti neçə km/saatdır?", d: "Ç", a: "50 km/saat" },
  { q: "3⁴ = ?", d: "A", a: "81" },
  { q: "Bir ədədin 25%-i 45-dirsə, ədədin özü neçədir?", d: "O", a: "180" },
  { q: "İki ədədin EKOB-u 60, EBOB-u 5-dir. Ədədlərdən biri 15-dirsə, digəri neçədir?", d: "Ç", a: "20" },
  { q: "−15 : 3 = ?", d: "A", a: "−5" },
  { q: "2/3 və 3/4 kəsrlərindən hansı böyükdür?", d: "O", a: "3/4" },
  { q: "Koordinat müstəvisində A(3, −2) nöqtəsi hansı rübdədir?", d: "Ç", a: "IV rüb" },
  { q: "5³ − 100 = ?", d: "A", a: "25" },
  { q: "Bir ədədin yarısından 5 çıxsaq, 10 alınır. Bu ədəd hansıdır?", d: "O", a: "30" },
  { q: "Üç ədədin nisbəti 2:3:5-dir, cəmləri 100-dür. Ən böyük ədəd hansıdır?", d: "Ç", a: "50" },
  { q: "−20 + (−15) = ?", d: "A", a: "−35" },
  { q: "Radiusu 5 sm olan dairənin sahəsi neçədir (π ≈ 3,14, S = πr²)?", d: "O", a: "78,5 sm²" },
  { q: "Mal 15% ucuzlaşdırılıb və indi 170 manata satılır. İlkin qiymət neçə idi?", d: "Ç", a: "200 manat" },
  { q: "7 × (−9) = ?", d: "A", a: "−63" },
  { q: "3, 7, 9, 2, 5 ədədlərinin medianını tap.", d: "O", a: "5" },
  { q: "Zəngli saat hər saat 2 dəqiqə geri qalır. 6 saat əvvəl ikisi də düzgün idisə, əsl saat 12:00 göstərəndə bu saat nə göstərir?", d: "Ç", a: "11:48" },
  { q: "−4 − (−9) = ?", d: "A", a: "5" },
  { q: "500 manata illik 8% faiz tətbiq olunur. 1 ilin faizi neçədir?", d: "O", a: "40 manat" },
  { q: "Xəritədə iki bənd arası 5 sm-dir, miqyas 1:200000-dir. Əsl məsafə neçə km-dir?", d: "Ç", a: "10 km" },
  { q: "2⁵ = ?", d: "A", a: "32" },
  { q: "Tərəfi 6 sm olan kubun həcmi neçədir?", d: "O", a: "216 sm³" },
  { q: "x/4 + 7 = 15 tənliyini həll et.", d: "Ç", a: "x = 32" },
  { q: "−18 : (−6) = ?", d: "A", a: "3" },
  { q: "7 ədədin ortalaması (arifmetik ortası) 20-dir. Bu ədədlərin cəmi neçədir?", d: "O", a: "140" },
  { q: "5(x + 3) − 2x ifadəsini sadələşdir.", d: "Ç", a: "3x + 15" },
  { q: "100 − (−50) = ?", d: "A", a: "150" },
  { q: "40 əşyanı 3:5 nisbətində böl. Böyük hissə neçədir?", d: "O", a: "25" },
  { q: "4 işçi bir işi 6 gündə görürsə, 8 işçi eyni işi neçə gündə görər?", d: "Ç", a: "3 gün" },
  { q: "−7 × 0 = ?", d: "A", a: "0" },
  { q: "Bir ədədin kubu 27-dir. Bu ədəd hansıdır?", d: "O", a: "3" },
  { q: "Otağın uzunluğu 8 m, eni 6 m, hündürlüyü 3 m-dir. Həcmi neçə m³-dür?", d: "Ç", a: "144 m³" },
  { q: "6 − 10 = ?", d: "A", a: "−4" },
  { q: "45 dəqiqə bir saatın neçə faizidir?", d: "O", a: "75%" },
  { q: "İki ədədin cəmi 50-dir, nisbəti 2:3-dür. Kiçik ədəd hansıdır?", d: "Ç", a: "20" },
  { q: "(−3)² = ?", d: "A", a: "9" },
  { q: "120-nin 5%-i neçədir?", d: "O", a: "6" },
  { q: "3, 6, 12, 24, … ardıcıllığının 6-cı hədidi neçədir?", d: "Ç", a: "96" },
  { q: "−25 + 30 = ?", d: "A", a: "5" },
  { q: "Əsası 10 sm, hündürlüyü 6 sm olan üçbucağın sahəsi neçədir?", d: "O", a: "30 sm²" },
  { q: "Qırmızı və göy avtomobillərin nisbəti 5:3-dür. Qırmızılar göydən 18 ədəd çoxdur. Cəmi neçə avtomobil var?", d: "Ç", a: "72" },
  { q: "8 × 8 − 20 = ?", d: "A", a: "44" },
  { q: "2 saat 30 dəqiqə neçə dəqiqədir?", d: "O", a: "150" },
  { q: "Bir ədədin 1/3 hissəsinin 2 qatı 20-dir. Bu ədəd hansıdır?", d: "Ç", a: "30" },
  { q: "−9 + (−9) = ?", d: "A", a: "−18" },
  { q: "4, 7, 4, 9, 4 ədədlərinin modasını (ən çox təkrarlananını) tap.", d: "O", a: "4" },
  { q: "İki ədədin hasili 96, EBOB-u 4-dür. EKOB-u neçədir?", d: "Ç", a: "24" },
  { q: "10² − 5² = ?", d: "A", a: "75" },
  { q: "Diametri 10 sm olan dairənin sahəsi neçədir (π ≈ 3,14)?", d: "O", a: "78,5 sm²" },
  { q: "Bir işi 6 nəfər 10 gündə görürsə, 15 nəfər neçə gündə görər?", d: "Ç", a: "4 gün" },
  { q: "−6 × 6 = ?", d: "A", a: "−36" },
  { q: "Üç ədədin nisbəti 1:2:3-dür, cəmləri 72-dir. Orta ədəd hansıdır?", d: "O", a: "24" },
  { q: "A = {2, 4, 6, 8, 10} və B = {4, 8, 12} çoxluqları verilib. A\\B (A-nın B-də olmayan elementləri) hansılardır?", d: "Ç", a: "{2, 6, 10}" }
];
