var QUIZ_META = { title: "8-ci sinif üçün məntiq testi", grade: 8 };

var QUESTIONS = [
  { q: "√49 = ?", d: "A", a: "7" },
  { q: "√2 ədədi hansı iki ardıcıl tam ədəd arasında yerləşir?", d: "A", a: "1 və 2" },
  { q: "√18 ifadəsini sadə radikal şəklində yaz.", d: "O", a: "3√2" },
  { q: "√50 + √8 ifadəsini sadələşdir.", d: "Ç", a: "7√2" },
  { q: "√16 · √4 = ?", d: "A", a: "8" },
  { q: "√72 : √2 = ?", d: "O", a: "6" },
  { q: "(√3 + 2)(√3 − 2) ifadəsini sadələşdir.", d: "Ç", a: "−1" },
  { q: "3:5 = x:20 tənasübündə x neçədir?", d: "A", a: "12" },
  { q: "Mal 40% qazancla 700 manata satılıb. Alış qiyməti neçə idi?", d: "O", a: "500 manat" },
  { q: "İki kəmiyyət tərs mütənasibdir. Birinci 6 olduqda ikincisi 8-dir. Birinci 4 olduqda ikinci neçədir?", d: "Ç", a: "12" },
  { q: "√10 ədədi 3-ə, yoxsa 4-ə daha yaxındır?", d: "A", a: "3-ə (3.16 olduğu üçün)" },
  { q: "x² = 49 tənliyini həll et.", d: "A", a: "x = 7 və ya x = −7" },
  { q: "x² − 5x + 6 = 0 tənliyini həll et.", d: "O", a: "x = 2 və ya x = 3" },
  { q: "2x² − 7x + 3 = 0 tənliyini həll et.", d: "Ç", a: "x = 3 və ya x = 1/2" },
  { q: "x² − 9 = 0 tənliyini həll et.", d: "A", a: "x = 3 və ya x = −3" },
  { q: "x² + 4x = 0 tənliyini həll et.", d: "O", a: "x = 0 və ya x = −4" },
  { q: "Sərbəst düşən cisim h = 5t² düsturu ilə hərəkət edir. 3 saniyədən sonra neçə metr yol getmiş olar?", d: "Ç", a: "45 metr" },
  { q: "2x − 5 < 7 bərabərsizliyini həll et.", d: "A", a: "x < 6" },
  { q: "3x + 4 ≥ x − 2 bərabərsizliyini həll et.", d: "O", a: "x ≥ −3" },
  { q: "|x − 2| < 5 bərabərsizliyinin həllini tap.", d: "Ç", a: "−3 < x < 7" },
  { q: "Düzbucaqlı üçbucağın katetləri 3 sm və 4 sm-dir. Hipotenuz neçədir?", d: "A", a: "5 sm" },
  { q: "Düzbucaqlı üçbucağın hipotenuzu 13 sm, bir kateti 5 sm-dir. Digər katet neçədir?", d: "O", a: "12 sm" },
  { q: "Düzbucaqlı üçbucağın katetləri bərabərdir, hipotenuzu 10√2 sm-dir. Katetin uzunluğu neçədir?", d: "Ç", a: "10 sm" },
  { q: "sin 30° = ?", d: "A", a: "1/2" },
  { q: "cos 45° = ?", d: "O", a: "√2/2" },
  { q: "tan 60° = ?", d: "Ç", a: "√3" },
  { q: "Paraleloqramın qarşı tərəfləri necə münasibətdədir?", d: "A", a: "Bərabər və paraleldir" },
  { q: "Paraleloqramın bir bucağı 70°-dir. Ona qonşu bucaq neçədir?", d: "O", a: "110°" },
  { q: "Paraleloqramın diaqonalları kəsişmə nöqtəsində necə bölünür?", d: "Ç", a: "Yarıya bölünür" },
  { q: "Üçbucağın əsası 10 sm, hündürlüyü 6 sm-dir. Sahəsi neçədir?", d: "A", a: "30 sm²" },
  { q: "Paraleloqramın əsası 8 sm, hündürlüyü 5 sm-dir. Sahəsi neçədir?", d: "O", a: "40 sm²" },
  { q: "Rombun diaqonalları 6 sm və 8 sm-dir. Sahəsi neçədir?", d: "Ç", a: "24 sm²" },
  { q: "Trapesiyanın oturacaqları 6 sm və 10 sm, hündürlüyü 4 sm-dir. Sahəsi neçədir?", d: "A", a: "32 sm²" },
  { q: "Kvadratın diaqonalı 8 sm-dir. Sahəsi neçədir?", d: "O", a: "32 sm²" },
  { q: "Üçbucağın sahəsi 60 sm², əsası 12 sm-dir. Hündürlüyü neçədir?", d: "Ç", a: "10 sm" },
  { q: "A(2, 3) və B(6, 7) nöqtələri arasındakı parçanın orta nöqtəsi hansıdır?", d: "A", a: "(4, 5)" },
  { q: "M(−2, 5) və N(4, −3) nöqtələri arasındakı parçanın orta nöqtəsi hansıdır?", d: "O", a: "(1, 1)" },
  { q: "A(1, 2) və B(5, 6) nöqtələrindən keçən düz xəttin tənliyini yaz (y = kx + b şəklində).", d: "Ç", a: "y = x + 1" },
  { q: "√25 + √36 = ?", d: "A", a: "11" },
  { q: "√48 ifadəsini sadə radikal şəklində yaz.", d: "O", a: "4√3" },
  { q: "3√2 · 2√8 ifadəsini sadələşdir.", d: "Ç", a: "24" },
  { q: "x² = 100 tənliyini həll et.", d: "A", a: "x = 10 və ya x = −10" },
  { q: "x² − 7x + 12 = 0 tənliyini həll et.", d: "O", a: "x = 3 və ya x = 4" },
  { q: "x² + 2x − 15 = 0 tənliyini həll et.", d: "Ç", a: "x = −5 və ya x = 3" },
  { q: "4x + 3 > 15 bərabərsizliyini həll et.", d: "A", a: "x > 3" },
  { q: "5 − 2x ≤ 11 bərabərsizliyini həll et.", d: "O", a: "x ≥ −3" },
  { q: "|3x + 1| ≥ 7 bərabərsizliyinin həllini tap.", d: "Ç", a: "x ≥ 2 və ya x ≤ −8/3" },
  { q: "Düzbucaqlı üçbucağın katetləri 6 sm və 8 sm-dir. Hipotenuz neçədir?", d: "A", a: "10 sm" },
  { q: "Düzbucaqlı üçbucağın hipotenuzu 25 sm, bir kateti 15 sm-dir. Digər katet neçədir?", d: "O", a: "20 sm" },
  { q: "Kvadratın tərəfi a-dır. Diaqonalını a ilə ifadə et.", d: "Ç", a: "a√2" },
  { q: "cos 0° = ?", d: "A", a: "1" },
  { q: "sin 90° = ?", d: "O", a: "1" },
  { q: "sin 30° + cos 60° = ?", d: "Ç", a: "1" },
  { q: "Paraleloqramın diaqonalları kəsişmə nöqtəsində necə xüsusiyyətə malikdir?", d: "A", a: "Kəsişmə nöqtəsində yarıya bölünürlər" },
  { q: "Rombun bütün tərəfləri necə münasibətdədir?", d: "O", a: "Bərabərdir" },
  { q: "Bucaqlarından biri 90° olan paraleloqramın (düzbucaqlının) tərəfləri 8 sm və 12 sm-dir. Sahəsi neçədir?", d: "Ç", a: "96 sm²" },
  { q: "√100 − √64 = ?", d: "A", a: "2" },
  { q: "Trapesiyanın oturacaqları 5 sm və 9 sm, sahəsi 42 sm²-dir. Hündürlüyü neçədir?", d: "O", a: "6 sm" },
  { q: "A(3, 5) nöqtəsi koordinat başlanğıcı ətrafında 90° (saat əqrəbinin əksinə) döndərilir: (x, y) → (−y, x). Yeni nöqtənin koordinatları hansıdır?", d: "Ç", a: "(−5, 3)" },
  { q: "√81 − √16 = ?", d: "A", a: "5" }
];
