var QUIZ_META = { title: "9-ci sinif üçün məntiq testi", grade: 9 };

var QUESTIONS = [
  { q: "∛8 = ?", d: "A", a: "2" },
  { q: "∛27 = ?", d: "A", a: "3" },
  { q: "∛64 · ∛8 ifadəsini sadələşdir.", d: "O", a: "8" },
  { q: "⁴√16 · ⁴√16 ifadəsini sadələşdir.", d: "Ç", a: "4" },
  { q: "a^(1/2) ifadəsi hansı kök işarəsinə bərabərdir?", d: "A", a: "√a" },
  { q: "8^(1/3) = ?", d: "O", a: "2" },
  { q: "27^(2/3) = ?", d: "Ç", a: "9" },
  { q: "Bir malın qiyməti 25% artırılıb və indi 500 manatdır. İlkin qiymət neçə idi?", d: "A", a: "400 manat" },
  { q: "800 manat kredit illik 12% sadə faizlə 3 ay üçün götürülüb. Faiz məbləği neçədir?", d: "O", a: "24 manat" },
  { q: "Mal əvvəlcə 30% ucuzlaşdırılıb, sonra yeni qiymətdən 20% baha satılıb. Son qiymət ilkin qiymətdən neçə % fərqlənir?", d: "Ç", a: "16% aşağı (84% qalır)" },
  { q: "√50 ədədi hansı iki ardıcıl tam ədəd arasındadır?", d: "A", a: "7 və 8" },
  { q: "∛100 ədədi hansı iki ardıcıl tam ədəd arasındadır?", d: "O", a: "4 və 5" },
  { q: "x + y = 8, x − y = 2 tənliklər sistemini həll et.", d: "A", a: "x = 5, y = 3" },
  { q: "2x + 3y = 19, x − y = 2 tənliklər sistemini həll et.", d: "O", a: "x = 5, y = 3" },
  { q: "x² + y² = 25, x + y = 7 tənliklər sistemini həll et.", d: "Ç", a: "x = 3, y = 4 və ya x = 4, y = 3" },
  { q: "3, 7, 11, 15, … arifmetik silsiləsinin növbəti hədi hansıdır?", d: "A", a: "19" },
  { q: "Arifmetik silsilənin ilk hədi 5, fərqi 4-dür. 10-cu hədi neçədir?", d: "O", a: "41" },
  { q: "Həndəsi silsilənin ilk hədi 3, məxrəci 2-dir. İlk 5 hədin cəmini tap.", d: "Ç", a: "93" },
  { q: "2, 6, 18, 54, … həndəsi silsiləsinin növbəti hədi hansıdır?", d: "A", a: "162" },
  { q: "Arifmetik silsilənin ilk 10 hədinin cəmi neçədir (a₁ = 2, d = 3)?", d: "O", a: "155" },
  { q: "x² − 5x + 4 > 0 kvadrat bərabərsizliyini həll et.", d: "Ç", a: "x < 1 və ya x > 4" },
  { q: "x² − 4 ≤ 0 bərabərsizliyini həll et.", d: "A", a: "−2 ≤ x ≤ 2" },
  { q: "x² − x − 6 < 0 bərabərsizliyini həll et.", d: "O", a: "−2 < x < 3" },
  { q: "x + y ≤ 10, x − y ≥ 2 bərabərsizliklər sistemi verilib. (6, 3) nöqtəsi bu sistemin həllidirmi?", d: "Ç", a: "Bəli (9 ≤ 10 və 3 ≥ 2 doğrudur)" },
  { q: "Üçbucağın daxilinə çəkilmiş çevrənin mərkəzi necə adlanır?", d: "A", a: "İnsentr (bissektrisaların kəsişmə nöqtəsi)" },
  { q: "Üçbucağın xaricinə çəkilmiş çevrənin mərkəzi necə tapılır?", d: "O", a: "Tərəflərin orta perpendikulyarlarının kəsişmə nöqtəsi" },
  { q: "Çevrəyə xaricdən çəkilmiş toxunan parçaları necə münasibətdədir?", d: "Ç", a: "Bərabərdir" },
  { q: "Çevrəyə toxunan xətt radiusla neçə dərəcəlik bucaq əmələ gətirir?", d: "A", a: "90°" },
  { q: "Çevrənin radiusu 5 sm-dir. Mərkəzdən 13 sm məsafədə olan nöqtədən çevrəyə çəkilən toxunanın uzunluğu neçədir?", d: "O", a: "12 sm" },
  { q: "a(2, 3) və b(4, 1) vektorları verilib. a + b vektoru hansıdır?", d: "A", a: "(6, 4)" },
  { q: "a(5, 7) və b(2, 3) vektorları verilib. a − b vektoru hansıdır?", d: "O", a: "(3, 4)" },
  { q: "a(3, 4) vektorunun uzunluğunu (modulunu) tap.", d: "Ç", a: "5" },
  { q: "a(3, 5) vektorunu 2 dəfə böyütsək (2a), nəticə hansıdır?", d: "A", a: "(6, 10)" },
  { q: "Paralel köçürmə zamanı A(2, 3) nöqtəsi (5, −1) vektoru ilə köçürülür. Yeni nöqtə hansıdır?", d: "O", a: "(7, 2)" },
  { q: "A(1, 2) nöqtəsi B(4, 6) nöqtəsinə köçürülən paralel köçürmə ilə C(3, 5) nöqtəsi hara köçür?", d: "Ç", a: "(6, 9)" },
  { q: "A(0, 0) və B(3, 4) nöqtələri arasındakı məsafəni tap.", d: "A", a: "5" },
  { q: "M(1, 2) və N(4, 6) nöqtələri arasındakı məsafəni tap.", d: "O", a: "5" },
  { q: "Mərkəzi (2, −3) olan və radiusu 4 olan çevrənin tənliyini yaz.", d: "Ç", a: "(x − 2)² + (y + 3)² = 16" },
  { q: "(x − 1)² + (y − 2)² = 9 çevrəsinin mərkəzi və radiusu hansıdır?", d: "A", a: "Mərkəz (1, 2), radius 3" },
  { q: "Mərkəzi koordinat başlanğıcında olan və A(3, 4) nöqtəsindən keçən çevrənin tənliyini yaz.", d: "O", a: "x² + y² = 25" },
  { q: "Mərkəzi (1, 1) olan çevrə A(4, 5) nöqtəsindən keçir. Çevrənin tənliyini yaz.", d: "Ç", a: "(x − 1)² + (y − 1)² = 25" },
  { q: "1 km neçə metrdir?", d: "A", a: "1000" },
  { q: "1 sm³ neçə mm³-dür?", d: "O", a: "1000" },
  { q: "2 saat 15 dəqiqəni saniyə ilə ifadə et.", d: "Ç", a: "8100 saniyə" },
  { q: "5 element arasından 3-ünü seçmək neçə üsulla mümkündür (sıra önəmli deyil)?", d: "A", a: "10" },
  { q: "4 kitabı bir rəfdə neçə fərqli sırada düzmək olar?", d: "O", a: "24" },
  { q: "Bir qutuda 6 top var, onlardan 2-si qırmızıdır. Təsadüfən 1 top çıxarılır. Qırmızı top çıxma ehtimalı neçədir?", d: "Ç", a: "1/3" },
  { q: "3 sikkə atılır. Cəmi neçə mümkün nəticə var?", d: "A", a: "8" },
  { q: "2 zər atılır. İkisinin cəminin 7 olma ehtimalını tap.", d: "O", a: "1/6" },
  { q: "5 nəfərdən 2 nəfərlik komissiya seçilir (sıra önəmsiz). Neçə fərqli komissiya yaratmaq olar?", d: "Ç", a: "10" },
  { q: "Statistik məlumatlarda ən çox təkrarlanan qiymətə nə deyilir?", d: "A", a: "Moda" },
  { q: "3, 5, 7, 9, 11 ədədlərinin ədədi ortasını (mean) tap.", d: "O", a: "7" },
  { q: "10 ədədin cəmi 252-dir. Bu ədədlərdən dəyəri 27 olanı çıxarsaq, qalan 9 ədədin ortalaması neçə olar?", d: "Ç", a: "25" },
  { q: "x² = 16 tənliyini həll et.", d: "A", a: "x = 4 və ya x = −4" },
  { q: "x² + 2x − 8 = 0 tənliyini həll et.", d: "O", a: "x = −4 və ya x = 2" },
  { q: "x² − 6x + 5 ≤ 0 bərabərsizliyini həll et.", d: "Ç", a: "1 ≤ x ≤ 5" },
  { q: "4, 8, 12, 16, … silsiləsinin 6-cı hədi neçədir?", d: "A", a: "24" },
  { q: "Həndəsi silsilənin ilk hədi 2, məxrəci 3-dür. 4-cü hədi neçədir?", d: "O", a: "54" },
  { q: "Arifmetik silsilənin 3-cü hədi 11, 7-ci hədi 27-dir. Fərqi (d) tapın.", d: "Ç", a: "4" },
  { q: "6 sikkə eyni zamanda atılanda cəmi neçə mümkün nəticə var?", d: "A", a: "64" }
];
